### ISSUE TITLE
大佬你这个还需要配置什么呀？直接部署到re或者vercel好像不行

### ISSUE THREAD

**Issue by xlenco** [zkeq/Bing-Wallpaper-Action#2]
希望大佬在后面能出个教程

**Comment by zkeq** [comment]
直接用我的爬虫爬好的数据不就行了，你要实现什么效果？

https://icodeq.com/bing/

这样的吗？

**Comment by zkeq** [comment]
hexo的话定时跑一下这个文件就行了

https://github.com/zkeq/Coding/blob/main/tools/bing.py

**Comment by zkeq** [comment]
本项目反正跑出来的东西都一样

成品在data目录下 

没必要自己部署 直接用我整理好的数据就行了

**Comment by zkeq** [comment]
https://raw.onmicrosoft.cn/Bing-Wallpaper-Action/main/data/zh-CN_all.json

这是成品

**Comment by xlenco** [comment]
谢了，不过你知道pixiv吗？我发现几个项目，还可以。
https://github.com/FreeNowOrg/PixivNow

**Comment by xlenco** [comment]
http://bing.icodeq.com/
这个怎么实现的

**Comment by xlenco** [comment]
### Actions中
下面是什么含义
  - name: 'Install requirements'
        run: |
          pip install -r ./tools/requirements.txt
      - name: 'GET BING'
        env:

-           PASSWORD: ${{ secrets.PASSWORD }}

**Comment by zkeq** [comment]
设置python需要的运行环境（requirements）

**Comment by zkeq** [comment]
> http://bing.icodeq.com/ 这个怎么实现的

很简单
https://github.com/zkeq/Bing-Wallpaper-Action/blob/0ce79c8ba49ae62f1d80646cb710f9ecfacba7fa/api/index.py#L16-L20

只不过目前我运行在 replit 上，通过vercel反代的。

**Comment by xlenco** [comment]
我看到你的自动部署workflows，但是下面这个变量添什么呢？
PASSWORD: ${{ secrets.PASSWORD }}

https://github.com/xlenco/Blog/blob/main/.github/workflows/bing.yml

**Comment by zkeq** [comment]
> 我看到你的自动部署workflows，但是下面这个变量添什么呢？ PASSWORD: ${{ secrets.PASSWORD }}
> 
> https://github.com/xlenco/Blog/blob/main/.github/workflows/bing.yml

redis的密码

**Comment by xlenco** [comment]
这个要怎么获取？自己搞一个？

**Comment by zkeq** [comment]
建议自己看源码，不提供此项目自建流程。

**Comment by zkeq** [comment]
https://github.com/zkeq/Bing-Wallpaper-Action/blob/0ce79c8ba49ae62f1d80646cb710f9ecfacba7fa/post_to_redis.py#L8-L14

**Comment by zkeq** [comment]
其实数据库直接读取data目录下的json文件就可以

不用redis数据库也可以

随便用py写写就行

再次重申本项目主要为提供data目录下的api成品，要想用直接拿我跑好的json用就行了

没必要自己部署

要想自己二开遵循开源协议即可

issues是提bug的，非功能问题不要提问

本项目还在数据采集积累阶段

相关问题不接受提问。

**Comment by zkeq** [comment]
> 本项目反正跑出来的东西都一样
> 
> 成品在data目录下
> 
> 没必要自己部署 直接用我整理好的数据就行了

没看见这个？

**Comment by xlenco** [comment]
https://github.com/zkeq/Coding/blob/main/.github/workflows/main.yml
         我如果用json,这个要改吧？
      - name: 'GET BING'
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

**Comment by zkeq** [comment]
这两行没用

我一直以为你是想部署这个爬虫 

你要部署博客早说呀，这个简单，去 #3 回复吧
