### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by xlenco** [zkeq/Bing-Wallpaper-Action#3]
我这hexo workflows自动部署用你的数据也要配置数据库吗？
https://github.com/xlenco/Blog/blob/main/.github/workflows/bing.yml

**Comment by xlenco** [comment]
没看到你发的

**Comment by zkeq** [comment]
擦，搞了半天，你是在搞博客？

**Comment by zkeq** [comment]
https://github.com/xlenco/Blog/blob/25bb53ec2a74fc70b41750963c5e8e647994ca5e/.github/workflows/bing.yml#L30-L31

把这两行删了就完事了，没用

**Comment by zkeq** [comment]
然后你运行一下actions

之后成功commit之后 在你网站就会出现 /bing/
目录

就配置成功了

**Comment by xlenco** [comment]
好的，😂我说啥感觉我们聊的不是一个东西
还正在揣摩你说的
之前确实想自己部署，不过这不是有现成的吗！

**Comment by zkeq** [comment]
你试试能不能跑起来

**Comment by zkeq** [comment]
你跑一下看看啊，等半天了(())

**Comment by xlenco** [comment]
稍等一下，有点问题，我检查一下

**Comment by xlenco** [comment]
![Screenshot_20220720_233451](https://user-images.githubusercontent.com/75837117/180023707-258a631e-1509-412c-8758-2574a5dd6e69.jpg)
但是source内没有bing目录

**Comment by zkeq** [comment]
> ![Screenshot_20220720_233451](https://user-images.githubusercontent.com/75837117/180023707-258a631e-1509-412c-8758-2574a5dd6e69.jpg) 但是source内没有bing目录

自己新建一个

**Comment by xlenco** [comment]
貌似还是不行，有可能和另一个
workflows有冲突，我改改看

**Comment by zkeq** [comment]
？？什么冲突

**Comment by zkeq** [comment]
我看看

**Comment by xlenco** [comment]
https://github.com/xlenco/Blog/
搞了个自动部署的workflows

**Comment by zkeq** [comment]
不是啊 我这个actions没有监听推送

**Comment by zkeq** [comment]
你要手动触发或者定时，到了时间自动触发

**Comment by zkeq** [comment]
你那个自动部署是监听的推送行为，只要有推送就会触发，在yaml前几行就是说这个的

**Comment by xlenco** [comment]
https://github.com/xlenco/Blog/runs/7433027180?check_suite_focus=true
报错

**Comment by zkeq** [comment]
> https://github.com/xlenco/Blog/runs/7433027180?check_suite_focus=true 报错

你这也不是最新的bing.yaml啊

**Comment by zkeq** [comment]
在你的bing.yaml里
加上这一行
https://github.com/zkeq/icodeq-bpi/blob/b8c6fffcdf46a4531738fb5f519b41d0a7fa09a5/.github/workflows/parwix-2H.yml#L10-L11

你在actions页面就会看到这个，就可以手动触发了
![Screenshot_2022-07-21-00-05-22-1226915780](https://user-images.githubusercontent.com/62864752/180030128-ef5556ec-9fe2-4423-8a4e-c64ac7f8fc00.png)

**Comment by zkeq** [comment]
bpi权限开放了

**Comment by zkeq** [comment]
好困，我先睡了

**Comment by xlenco** [comment]
昨天是我草率了，你辛苦了

**Comment by xlenco** [comment]
OK了

**Comment by xlenco** [comment]
https://github.com/xlenco/Blog/tree/main/source/Gallery/bing
