### ISSUE TITLE
action过程中遇到的问题

### ISSUE THREAD

**Issue by it985** [zkeq/Bing-Wallpaper-Action#4]
在部署action时
Error: GPG private key required
请问这个怎么解决

**Comment by flow2000** [comment]
没加密钥，密钥路径：https://github.com/用户名/仓库/settings/secrets/actions

**Comment by it985** [comment]
> 
不行，还是爆这个错
https://github.com/it985/Bing-Wallpaper-Action/actions
![image](https://user-images.githubusercontent.com/62421120/192924612-c84a9a96-57be-4d8e-b74e-faf3c776f493.png)

**Comment by flow2000** [comment]
那就不知道了，问问仓库创建人吧

**Comment by zkeq** [comment]
没必要自己部署...

跑出来数据反正都一样...

你这个配置错了:

```
GPG_PRIVATE_KEY
GPG_PASSPHRASE
```

这两个值是 https://github.com/crazy-max/ghaction-import-gpg 这个项目给的

不要自己改 `env` 里面的名字

<img width="786" alt="未命名" src="https://user-images.githubusercontent.com/62864752/197327867-34bd98da-d71d-4808-baae-a98a0a48baf4.png">
