### ISSUE TITLE
随机API无法使用了

### ISSUE THREAD

**Issue by JeffreyZeng-dev** [zkeq/Bing-Wallpaper-Action#6]
An error occurred with this application.

ROUTER_EXTERNAL_TARGET_HANDSHAKE_ERROR

**Comment by zkeq** [comment]
随机API因为上游是replit 因政策调整暂停使用了 可以考虑自己搭建

**Comment by zkeq** [comment]
已更新文档 更换 `https://api.xsot.cn/bing?jump=true`
